{% set version = "2.1.1" %}

package:
  name: misaka
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/misaka/misaka-{{ version }}.tar.gz
  sha256: 62f35254550095d899fc2ab8b33e156fc5e674176f074959cbca43cf7912ecd7

build:
  number: 4
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cffi >=1.0.0
    - msinttypes  # [win]
  run:
    - python
    - cffi >=1.0.0

test:
  imports:
    - misaka

about:
  home: https://github.com/FSX/misaka
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  summary: 'A CFFI binding for Hoedown, a markdown parsing library.'
  dev_url: https://github.com/FSX/misaka
  doc_url: http://misaka.61924.nl/

extra:
  recipe-maintainers:
    - pmlandwehr
