travis:
  secure:
    BINSTAR_TOKEN: B93tJPoay+poCynealMsZbJn9wGAdXkZOt6RgNuSXU4FsBe6X0oajBzab2frTAO/wk86kF/PkHY8d3DeEPNUlT2rV3TH8h4dnvNvyjd15eqpO8jttHzuoJQdKx4OvKCwfx4R6apygQRoE4WVzmkX2ogoKMhwrBgwLuFv4MI/r2+mxTFxNtCAYYbW9FDlw2rPQXNkMVJpjIUb9fGoz44APhcUNi1gpuIRnxHeuO1JS5x1fKiopfZgABQgkuDyoIU3bBaIoviBHoIJcbznXB2uvidbNEBt5ks9OnqO0HrSdhBmiLNxOy3TmYUN5j75Qc8fanA0ltMo2tBhnTN1/XTNt/lK+6Ri6RngSw3AObR6gvEmP/DYBOEp/hTiY1XgNABISUAH1GCCWVD312Snor1MDQxT1w+KuIcOhdUoxW1ENQ28vGjXBSUv3sd8MJL5uUxoZzMT5qX2+xeUCf9CC/OccwPPP/WQbbW7BDQAGx1BZZ4OOMQF+3rI9wWvalF6aI1Y+eCqZFVXkc+sNcHZpVAf4smxOE+oNTRiHmLE3kGwhFVYx+3inRzrOtBReg2hNj9S+1PVul9H9XL3WpB1YTI29qwzUEFLhvdIRGi/tU2TJ3pwSQIx25iku60CQ6yYdSio+r20TPAfYfjaQangytNBXgUY+XxqvEPIrtMagoDFOoI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
