travis:
  secure:
    BINSTAR_TOKEN: jXFzuYzBhjk0yilQr6BOOXWLfevDOs+emuCCF+1tNS7+n7GhmyVvnfquLdHyd4CtxsMGRN5YkkSe9jzRmwLPMTb6uIpJQ9oDXIcCjFmQaNHLjS4WdwNjuvYoGC3Awltc6Lr9saazZO3Is08Wz/8u27qePSFl7BbV6/f296R0Pnn9mdVYeHzdmZqAd2uwgWv2VjdYRw3VN2HU3FoLFOe7kf1MYwEyPP16UqOM6M0spyQwKQE35evOk1USXAYwSzoo3N7ePYknbsDJZ+nHTkGg2Fv9WYaeqhVZ0nFB8lBK615O7+xzD5K35B9J3PihwpUkNsHoMCpKhfEPzMi3/UkKUvUnZyM0gBY8ndNO+qQwNtvdTO88ccA+5N6MxPntYaae5EKFJbMcNa2fIYhdt/Le2B3C6kenilTf49Dn+QgfJl6+KGi5f6USUoG6Q78GIUAih8Ki22TBN1V+LtGHhYqzbrSFk2oF4YY+fVqbRjhmENiVmaA8xx2i90ApWCcTx6ZaXQ57/MaRKbQumMkuJNsMqMXPHcV26C6VgL6VEYfogCdjtjOQzjDPNqSPe6i+5cNL1PkitQe+fFSrqVnug53Xbq1xHDz35QTP9QwBOuCHo5KJGHCxiUKsh6GY1Mn/anqSkfmKqy8JsxGYsxiZcNYO3WDVpMQ3s2qE+cuhk0i7uY4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
